# Site settings
title: Joshua C. Detwiler
email: jdetwiler@vt.edu
description: "Computer Science Ph.D. student at Virginia Tech"
baseurl: ""
url: "https://jcdetwiler.github.io"
github_username: JCDetwiler
linkedin_username: joshua-detwiler
lang: "en"

headshot: "/assets/2018-04-20_headshot.png"

# Build settings
theme: minima

# Plugins
plugins:
  - github-pages
  - jekyll-last-modified-at

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
